## Kfold
kfold is validation and evulution process for the dataset. after getting the train and test data we put the Kfold Model it will shuffle all data by nich properties
and then will return the accuracy

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import  SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
import  matplotlib.pyplot as plt

digits = load_digits()

In [101]:
## dataset 

from sklearn.model_selection import train_test_split

X_train ,X_test , y_train,y_test = train_test_split(digits.data,
                                                   digits.target,
                                                   test_size = 0.3)

## logistic Regression

In [102]:
lr = LogisticRegression(solver="liblinear",multi_class="ovr")
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

0.9629629629629629

## SVM

In [103]:
svm = SVC(gamma="auto")
svm.fit(X_train, y_train)
svm.score(X_test,y_test)

0.35555555555555557

## Random Forest

In [104]:
rf = RandomForestClassifier(n_estimators=40)
rf.fit(X_train,y_train)
rf.score(X_test,y_test)

0.9740740740740741

## Kfold Cross Validation  
 basic EXample

In [105]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=4)
kf

KFold(n_splits=4, random_state=None, shuffle=False)

In [106]:
for train_index ,test_index  in kf.split([1,2,3,4,8,5,6,9]):
    print(train_index,test_index)

[2 3 4 5 6 7] [0 1]
[0 1 4 5 6 7] [2 3]
[0 1 2 3 6 7] [4 5]
[0 1 2 3 4 5] [6 7]


In [107]:
## se Kfold for our Digit example
def get_score(model , X_train ,X_test,y_train,y_test):
    
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)

In [108]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

scores_logistic = []
scores_svm = []
scores_rf = []

for train_index, test_index in folds.split(digits.data,digits.target):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], \
                                       digits.target[train_index], digits.target[test_index]
    scores_logistic.append(get_score(LogisticRegression(solver='liblinear',multi_class='ovr'), X_train, X_test, y_train, y_test))  
    scores_svm.append(get_score(SVC(gamma='auto'), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40), X_train, X_test, y_train, y_test))


In [109]:
scores_logistic

[0.8948247078464107, 0.9532554257095158, 0.9098497495826378]

In [110]:
scores_svm

[0.3806343906510851, 0.41068447412353926, 0.5125208681135225]

In [111]:
scores_rf

[0.9165275459098498, 0.9449081803005008, 0.9198664440734557]

## Cross val Score Function

In [112]:
from sklearn.model_selection import cross_val_score

## logistic regression model performance using Cross_val_score


In [113]:
cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'), digits.data, digits.target,cv=3)

array([0.89482471, 0.95325543, 0.90984975])

 ## SVM model performance using corss_val_Score
 
 

In [114]:
cross_val_score(SVC(gamma="auto"),digits.data,digits.target,cv=3)

array([0.38063439, 0.41068447, 0.51252087])

## Random forest Performance using Cross_val_Score

In [115]:
cross_val_score(RandomForestClassifier(n_estimators=40),digits.data,digits.target,cv=3)

array([0.93823038, 0.93489149, 0.91986644])

## Parameter Tunning using Fold Cross Validation


In [120]:
scores1 = cross_val_score(RandomForestClassifier(n_estimators=5),digits.data, digits.target, cv=10)
np.average(scores1)

0.8714494103041588

In [117]:
scores2 = cross_val_score(RandomForestClassifier(n_estimators=20),digits.data, digits.target, cv=10)
np.average(scores2)

0.9449037864680323

In [118]:
scores3 = cross_val_score(RandomForestClassifier(n_estimators=30),digits.data, digits.target, cv=10)
np.average(scores3)

0.9454686530105525

In [119]:
scores4 = cross_val_score(RandomForestClassifier(n_estimators=40),digits.data, digits.target, cv=10)
np.average(scores4)

0.9415735567970204