<a href="https://colab.research.google.com/github/iffishells/Data-Science/blob/main/Text-Mining-Reading_CsvFile.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ***Text Representation***

# ***For one Document***

In [ ]:
corpus  = ["I am interested in Data Science InshaAllah i will done it."]

In [ ]:
# !pip install sklearn # onnce
# !pip install -U scikit-learn

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
vec = CountVectorizer()  # vector

x = vec.fit_transform(corpus)
x

# 1 X 9 1 is documents and 9 is the number of the featuers
# because in the documents row are the number of the documents
# and columns are the number of the features



<1x9 sparse matrix of type '<class 'numpy.int64'>'
	with 9 stored elements in Compressed Sparse Row format>

In [ ]:
## binary representation not the frequeny !
x.toarray()

array([[1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [ ]:
# Get the features name form the documents
vec.get_feature_names()

['am',
 'data',
 'done',
 'in',
 'inshaallah',
 'interested',
 'it',
 'science',
 'will']

In [ ]:
# len of features name form the documents
len(vec.get_feature_names())

9

In [ ]:
## vacubulary of the documents
# key are the name of the features 
# value are the frequncy of the word
vec.vocabulary_

{'am': 0,
 'data': 1,
 'done': 2,
 'in': 3,
 'inshaallah': 4,
 'interested': 5,
 'it': 6,
 'science': 7,
 'will': 8}

In [ ]:
len(vec.vocabulary_)

9

# ***Multi Documents***

In [ ]:
corpus = ["text text text mining is interesting",
          'test mining is the same as data mining',
          "text and data have few difference"]


In [ ]:
from sklearn.feature_extraction.text import CountVectorizer


In [ ]:

vec  = CountVectorizer()

In [ ]:
x = vec.fit_transform(corpus)

In [ ]:
x.toarray()

array([[0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 3, 0],
       [0, 1, 1, 0, 0, 0, 0, 1, 2, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0]])

In [ ]:
vec.get_feature_names()

['and',
 'as',
 'data',
 'difference',
 'few',
 'have',
 'interesting',
 'is',
 'mining',
 'same',
 'test',
 'text',
 'the']

In [ ]:
len(vec.get_feature_names())

13

In [ ]:
vec.vocabulary_

{'and': 0,
 'as': 1,
 'data': 2,
 'difference': 3,
 'few': 4,
 'have': 5,
 'interesting': 6,
 'is': 7,
 'mining': 8,
 'same': 9,
 'test': 10,
 'text': 11,
 'the': 12}

# ***Parameters***

In [ ]:
# by setting the parameters you can extract the imformation
# according to your requirement like 'max_features ' mean how 
# you many want features

vec = CountVectorizer(binary ='true',
                      max_df=3,
                      min_df=1,
                      max_features=3,
                      ngram_range=(1,3))


vec.fit_transform(corpus)


<3x3 sparse matrix of type '<class 'numpy.int64'>'
	with 6 stored elements in Compressed Sparse Row format>

In [ ]:
vec.get_feature_names()

['is', 'mining is', 'text']

In [ ]:
vec.vocabulary_

{'is': 0, 'mining is': 1, 'text': 2}

# ***Term frequency–inverse document frequency***

In [ ]:
corpus = ['text text mining is interesting',
          'text mining is the same as data mining',
          'text and data mining have few differences']

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer


In [ ]:
vec = TfidfVectorizer(min_df=2,max_df=3,ngram_range=(1,3))

In [ ]:
x = vec.fit_transform(corpus)

In [ ]:
x.toarray()

array([[0.        , 0.        , 0.37754794, 0.29319966, 0.37754794,
        0.58639932, 0.37754794, 0.37754794],
       [0.33304752, 0.33304752, 0.33304752, 0.51728221, 0.33304752,
        0.25864111, 0.33304752, 0.33304752],
       [0.55847784, 0.55847784, 0.        , 0.43370786, 0.        ,
        0.43370786, 0.        , 0.        ]])

In [ ]:
vec.get_feature_names()

['data',
 'data mining',
 'is',
 'mining',
 'mining is',
 'text',
 'text mining',
 'text mining is']

In [ ]:
len(vec.get_feature_names())

8

In [ ]:
vec.vocabulary_

{'data': 0,
 'data mining': 1,
 'is': 2,
 'mining': 3,
 'mining is': 4,
 'text': 5,
 'text mining': 6,
 'text mining is': 7}

 # *Reading Data from File* 

---
Label Data


In [ ]:
corpus = open("/content/labelData.txt").read()
corpus

'Data mining is sexcy job : job\ndata scitents is tuff : tuff\ntext mining is interesint : mining\ndata engineer is owsem job : Enginering'

In [ ]:
docs = corpus.split("\n")

docs


['Data mining is sexcy job : job',
 'data scitents is tuff : tuff',
 'text mining is interesint : mining',
 'data engineer is owsem job : Enginering']

In [ ]:
x , y = [] , []

for doc in docs:
    print(doc)
    i , l  = doc.split(" : ")
    x.append(i.strip())
    y.append(l.strip())

Data mining is sexcy job : job
data scitents is tuff : tuff
text mining is interesint : mining
data engineer is owsem job : Enginering


In [ ]:
x

['Data mining is sexcy job',
 'data scitents is tuff',
 'text mining is interesint',
 'data engineer is owsem job']

In [ ]:
y

['job', 'tuff', 'mining', 'Enginering']

# ***Import data from Datasets UCI***

In [1]:
path = "/content/tripadvisor_review.csv"
corpus = open(path).read()
corpus

'User ID,Category 1,Category 2,Category 3,Category 4,Category 5,Category 6,Category 7,Category 8,Category 9,Category 10\nUser 1,0.93,1.8,2.29,0.62,0.8,2.42,3.19,2.79,1.82,2.42\nUser 2,1.02,2.2,2.66,0.64,1.42,3.18,3.21,2.63,1.86,2.32\nUser 3,1.22,0.8,0.54,0.53,0.24,1.54,3.18,2.8,1.31,2.5\nUser 4,0.45,1.8,0.29,0.57,0.46,1.52,3.18,2.96,1.57,2.86\nUser 5,0.51,1.2,1.18,0.57,1.54,2.02,3.18,2.78,1.18,2.54\nUser 6,0.99,1.28,0.72,0.27,0.74,1.26,3.17,2.89,1.66,3.66\nUser 7,0.9,1.36,0.26,0.32,0.86,1.58,3.17,2.66,1.22,3.22\nUser 8,0.74,1.4,0.22,0.41,0.82,1.5,3.17,2.81,1.54,2.88\nUser 9,1.12,1.76,1.04,0.64,0.82,2.14,3.18,2.79,1.41,2.54\nUser 10,0.7,1.36,0.22,0.26,1.5,1.54,3.17,2.82,2.24,3.12\nUser 11,1.47,1,0.7,0.75,1.66,2.76,3.18,2.89,1.66,2.62\nUser 12,0.96,2.96,0.29,0.38,0.88,2.08,3.17,2.93,1.66,3.42\nUser 13,0.74,1.44,2.75,0.45,0.98,1.74,3.2,2.87,1.38,2.34\nUser 14,0.58,1.64,2.27,0.45,1.26,1.72,3.19,2.91,2.3,2.74\nUser 15,0.96,1.68,2.29,0.51,1.2,2.84,3.2,2.82,2.02,2.46\nUser 16,1.25,2.52,1.76,0

In [2]:
docs = corpus.split("\n")

In [3]:
docs


['User ID,Category 1,Category 2,Category 3,Category 4,Category 5,Category 6,Category 7,Category 8,Category 9,Category 10',
 'User 1,0.93,1.8,2.29,0.62,0.8,2.42,3.19,2.79,1.82,2.42',
 'User 2,1.02,2.2,2.66,0.64,1.42,3.18,3.21,2.63,1.86,2.32',
 'User 3,1.22,0.8,0.54,0.53,0.24,1.54,3.18,2.8,1.31,2.5',
 'User 4,0.45,1.8,0.29,0.57,0.46,1.52,3.18,2.96,1.57,2.86',
 'User 5,0.51,1.2,1.18,0.57,1.54,2.02,3.18,2.78,1.18,2.54',
 'User 6,0.99,1.28,0.72,0.27,0.74,1.26,3.17,2.89,1.66,3.66',
 'User 7,0.9,1.36,0.26,0.32,0.86,1.58,3.17,2.66,1.22,3.22',
 'User 8,0.74,1.4,0.22,0.41,0.82,1.5,3.17,2.81,1.54,2.88',
 'User 9,1.12,1.76,1.04,0.64,0.82,2.14,3.18,2.79,1.41,2.54',
 'User 10,0.7,1.36,0.22,0.26,1.5,1.54,3.17,2.82,2.24,3.12',
 'User 11,1.47,1,0.7,0.75,1.66,2.76,3.18,2.89,1.66,2.62',
 'User 12,0.96,2.96,0.29,0.38,0.88,2.08,3.17,2.93,1.66,3.42',
 'User 13,0.74,1.44,2.75,0.45,0.98,1.74,3.2,2.87,1.38,2.34',
 'User 14,0.58,1.64,2.27,0.45,1.26,1.72,3.19,2.91,2.3,2.74',
 'User 15,0.96,1.68,2.29,0.51,1.2,2.8

In [4]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [18]:
vec = TfidfVectorizer(min_df=2 ,max_df=2)
vec

TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.float64'>, encoding='utf-8',
                input='content', lowercase=True, max_df=2, max_features=None,
                min_df=2, ngram_range=(1, 1), norm='l2', preprocessor=None,
                smooth_idf=True, stop_words=None, strip_accents=None,
                sublinear_tf=False, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, use_idf=True, vocabulary=None)

In [15]:
x = vec.fit_transform(docs)

In [16]:
x

<982x1 sparse matrix of type '<class 'numpy.float64'>'
	with 2 stored elements in Compressed Sparse Row format>

In [17]:
x.toarray()

array([[1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],